# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(related_name='decks', to='deck.Deck'),
        ),
    ]
