# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_decks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='decks',
        ),
    ]
