# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
        ('card', '0003_remove_card_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(related_name='decks', to='deck.Deck'),
        ),
    ]
