# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='card',
        ),
    ]
